# fly.toml app configuration file generated for joelm-website on 2024-12-02T15:17:13-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'joelm-website'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
